trigger:
- master

pool:
  vmImage: 'windows-2022'

variables:
  VCPKG_DIR: '$(Build.SourcesDirectory)\vcpkg'
  VCPKG_VERSION: '2021.05.12'

steps:
- script: |
    git clone https://github.com/microsoft/vcpkg %VCPKG_DIR%
    git %VCPKG_DIR% checkout tags/%VCPKG_VERSION%
    call %VCPKG_DIR%\bootstrap-vcpkg.bat
    %VCPKG_DIR%\vcpkg.exe integrate install
  displayName: 'Install vcpkg'

- script: |
    cd $(Build.SourcesDirectory)\Engine3D
    %VCPKG_DIR%\vcpkg.exe install
  displayName: 'vcpkg package installation'

- task: VSBuild@1
  inputs:
    vsVersion: 17.0
    solution: '$(Build.SourcesDirectory)\Engine3D\Engine3D.vcxproj'
    configuration: 'Release'
    platform: 'Win32'
  displayName: 'Build C++ Engine'

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(Build.SourcesDirectory)\EngineEditor\EngineEditor.csproj'

- task: VSBuild@1
  inputs:
    vsVersion: 17.0
    solution: '$(Build.SourcesDirectory)\EngineEditor\EngineEditor.csproj'
    configuration: 'Debug'
    platform: 'x86'
  displayName: 'Build C# Editor'
