# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x86'
  buildConfiguration: 'Release'
  VCPKG_DIR: '$(Build.SourcesDirectory)\vcpkg'
  VCPKG_VERSION: '2021.05.12'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- script: |
    git clone https://github.com/microsoft/vcpkg %VCPKG_DIR%
    git %VCPKG_DIR% checkout tags/%VCPKG_VERSION%
    call %VCPKG_DIR%\bootstrap-vcpkg.bat
    %VCPKG_DIR%\vcpkg.exe version
  displayName: 'Install vcpkg'

- script: |
    cd $(Build.SourcesDirectory)\Engine3D
    %VCPKG_DIR%\vcpkg.exe install --triplet x86-windows
  displayName: 'vcpkg package installation'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
